import { test } from "@playwright/test";
import { ProductsPage } from "../page-objects/ProductsPage";
import { Navigation } from "../page-objects/Navigation";
import { Checkout } from "../page-objects/Checkout";
import { LoginPage } from "../page-objects/LoginPage";
import { RegisterPage } from "../page-objects/RegisterPage";
import { DeliveryDetails } from "../page-objects/DeliveryDetails";
import { PaymentPage } from "../page-objects/PaymentPage";
import { deliveryDetails as userDetails } from "../data/deliveryDetails";
import { paymentDetails } from "../data/paymentDetails";
import { v4 as uuidv4 } from "uuid";

test.only("New user full end-to-end test journey", async ({ page }) => {
  const productsPage = new ProductsPage(page);
  await productsPage.visit();
  await productsPage.sortByCheapest();
  await productsPage.addProductToBasket(0);
  await productsPage.addProductToBasket(1);
  await productsPage.addProductToBasket(2);
  const navigation = new Navigation(page);
  await navigation.goToCheckout();
  const checkout = new Checkout(page);
  await checkout.removeCheapestProduct();
  await checkout.continueToCheckout();
  const loginPage = new LoginPage(page);
  await loginPage.moveToSignUp();
  const registerPage = new RegisterPage(page);
  const email = uuidv4() + "@test.com";
  const password = uuidv4();
  await registerPage.signUpAsNewUser(email, password);
  const deliveryDetails = new DeliveryDetails(page);
  await deliveryDetails.fillDetails(userDetails);
  await deliveryDetails.saveDetails();
  await deliveryDetails.continueToPayment();
  const paymentPage = new PaymentPage(page);
  await paymentPage.activateDiscount();
  await paymentPage.fillPaymentDetails(paymentDetails);
  // await page.pause();
});
