name: Playwright Tests
on:
  push:
    branches: [master]
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout repository
        uses: actions/checkout@v2
      - name: Say Hello
        run: echo Hello
