name: Playwright Tests
on:
  push:
    branches: [master]
jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.42.1-jammy
      env:
        USER: ${{secrets.USER}}
        ADMIN_PASSWORD: ${{secrets.ADMIN_PASSWORD}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run test
        run: |
          echo "Start the shopping store application"
          ./shopping-store-linux-amd64 &
          echo "Install dependencies from lock file"
          npm ci
          echo "Run playwright tests"
          npm run test:ci
