name: Playwright Tests
on:
  push:
    branches: [master]
jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Say Hello
        run: echo Hello
